=== EsmeraldaCanoOrtega/Web/b2xmlDtdXslt/P06/p06/aula/aula3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="curso">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="numero_aula" type="xs:string" />
                <xs:element name="horario">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dias">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="modulos">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="modulo"
                                                                    maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension
                                                                                base="xs:string">
                                                                                <xs:attribute
                                                                                    name="hora_inicio"
                                                                                    use="required" />
                                                                                <xs:attribute
                                                                                    name="hora_fin"
                                                                                    use="required" />
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="nombre" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="equipos_informaticos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ip" type="xs:string" />
                                        <xs:element name="mascara" type="xs:string" />
                                        <xs:element name="puerta_enlace" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="numero" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="alumnos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="alumno" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="pc">
                                            <xs:complexType>
                                                <xs:attribute name="numero" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="nombre" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EsmeraldaCanoOrtega/Web/b2xmlDtdXslt/P06/p06/aula/aula.xml
<?xml version="1.0" encoding="UTF-8"?>






<curso xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="aula3.xsd" 
>
    <nombre>ASD</nombre>
    <numero_aula>A21</numero_aula>
    <horario>
        <dias>
            <dia nombre="lunes">
                <modulos>
                    <modulo hora_inicio="8:30" hora_fin="10:20">ED</modulo>
                    <modulo hora_inicio="10:20" hora_fin="11:15">SI</modulo>
                    <modulo hora_inicio="11:40" hora_fin="14:25">PROG</modulo>
                </modulos>
            </dia>
            <dia nombre="martes">
                <modulos>
                    <modulo hora_inicio="8:30" hora_fin="10:20">BBDD</modulo>
                    <modulo hora_inicio="11:40" hora_fin="12:35">SI</modulo>
                    <modulo hora_inicio="12:35" hora_fin="14:25">LM</modulo>
                </modulos>
            </dia>
            <dia nombre="miercoles">
                <modulos>
                    <modulo hora_inicio="8:30" hora_fin="11:15">PROG</modulo>
                    <modulo hora_inicio="12:35" hora_fin="13:30">BBDD</modulo>
                    <modulo hora_inicio="13:30" hora_fin="14:25">ED</modulo>
                </modulos>
            </dia>
        </dias>
    </horario>
    <equipos_informaticos>
        <equipo numero="e001">
            <ip>10.20.20.100</ip>
            <mascara>5b:be:e2:bc:05:6a</mascara>
            <puerta_enlace>10.20.20.1</puerta_enlace>
        </equipo>
        <equipo numero="e002">
            <ip>10.20.20.100</ip>
            <mascara>99:5b:41:ad:08:23</mascara>
            <puerta_enlace>10.20.20.1</puerta_enlace>
        </equipo>
        <equipo numero="e003">
            <ip>10.20.20.100</ip>
            <mascara>39:a3:1f:0c:0c:59</mascara>
            <puerta_enlace>10.20.20.1</puerta_enlace>
        </equipo>
    </equipos_informaticos>
    <alumnos>
        <alumno nombre="Esmeralda Caño Ortega">
            <pc numero="e001"/>
        </alumno>
        <alumno nombre="Liliana Fernández Dacosta">
            <pc numero="e002"/>
        </alumno>
        <alumno nombre="Iván Rodrigo Illescas">
            <pc numero="e003"/>
        </alumno>
    </alumnos>
</curso>
